language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

matrix:
  allow_failures:
  - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - phpenv rehash
  - composer install --dev

before_script:
  - bin/phpcs --version

script:
  - if find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi
  - bin/phpcs --standard=PSR1,PSR2 --extensions=php -s \
    modules/guestbook \
    modules/helplet
  - bin/phpcs --standard=PSR1,PSR2 --extensions=php -s --exclude=Generic.Files.LineLength \
    modules/about \
    modules/beamer \
    modules/board \
    modules/codecheck \
    modules/downloads \
    modules/faq \
    modules/games \
    modules/hardware \
    modules/home \
    modules/info2 \
    modules/irc \
    modules/msgsys \
    modules/partylist \
    modules/paypal \
    modules/picgallery \
    modules/popups \
    modules/rent \
    modules/sample \
    modules/server \
    modules/shoutbox \
    modules/signon \
    modules/sponsor \
    modules/stats \
    modules/troubleticket \
    modules/wiki
  - bin/phpcs --standard=PSR1,PSR2 --extensions=php -s --exclude=Generic.Files.LineLength,PSR1.Methods.CamelCapsMethodName \
    modules/boxes \
    modules/bugtracker \
    modules/cashmgr \
    modules/clanmgr \
    modules/foodcenter \
    modules/guestlist \
    modules/install \
    modules/mail \
    modules/mastersearch2 \
    modules/news \
    modules/party \
    modules/poll \
    modules/seating \
    modules/tournament2 \
    modules/usrmgr
  - bin/phpcs --standard=PSR1,PSR2 --extensions=php -s --exclude=PSR1.Methods.CamelCapsMethodName modules/cron2
  - bin/phpcs --standard=PSR1,PSR2 --extensions=php -s --exclude=Generic.Files.LineLength,PSR2.Methods.MethodDeclaration,PSR1.Methods.CamelCapsMethodName modules/pdf
  - bin/phpcs --standard=PSR1,PSR2 --extensions=php -s --exclude=Generic.Files.LineLength,PSR2.Methods.MethodDeclaration,PSR1.Classes.ClassDeclaration modules/teamspeak2
  - bin/phpcs --standard=PSR1,PSR2 --extensions=php -s --ignore="/ext_scripts/*,/ext_inc/*,/modules/*,/vendor/*" . || true # Allow failures for now
  - bin/phpunit
