language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

matrix:
  allow_failures:
  - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - phpenv rehash
  - composer install --dev

before_script:
  - bin/phpcs --version
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_EVENT_TYPE

script:
  - CHANGED_FILES=($(git diff --name-only --diff-filter=ACM $TRAVIS_COMMIT~ $TRAVIS_COMMIT))
  - echo $CHANGED_FILES
  - for file in $CHANGED_FILES; do
    bin/phpcs --standard=PSR1,PSR2 --extensions=php -s $file;
    if php -l $file | grep -v "No syntax errors detected"; then exit 1; fi
    done
  - bin/phpunit
