language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

matrix:
  allow_failures:
  - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - phpenv rehash
  - composer install --dev

before_script:
  - bin/phpcs --version
  - CHANGED_FILES=($(git diff --name-only $TRAVIS_COMMIT_RANGE))
  - echo $CHANGED_FILES

script:
  - for file in $CHANGED_FILES; do
    bin/phpcs --standard=PSR1,PSR2 --extensions=php -s $file;
    done
  - if find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi
  - bin/phpunit
