name: Continuous Integration

on:
  push:
  schedule:
    - cron: "5 1 * * *"

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        # TODO Add experimental jobs
        php-versions: ['7.2', '7.3', '7.4']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd, mysqli
          #ini-values: post_max_size=256M, max_execution_time=180
          #coverage: xdebug
          #tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}

      #- name: Configure composer
      #  run: |
      #    COMPOSER_HOME="$(composer config home)"
      #    ([ -d "$COMPOSER_HOME" ] || mkdir "$COMPOSER_HOME") && cp .github/composer-config.json "$COMPOSER_HOME/config.json"
      #    echo "COMPOSER_ROOT_VERSION=$(grep branch-version composer.json | grep -o '[0-9.x]*').x-dev" >> $GITHUB_ENV

      - name: Determine composer cache directory
        id: composer-cache
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
            path: ${{ steps.composer-cache.outputs.directory }}
            key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: ${{ matrix.php }}-composer-

      - name: Install dependencies
        run: |
            echo "::group::composer update"
            composer require --dev --no-update mongodb/mongodb:@stable
            composer update --no-progress --ansi
            echo "::endgroup::"
            #echo "::group::install phpunit"
            #bin/phpunit install
            #echo "::endgroup::"

      - name: Run tests
        run: bin/phpunit
